
import type { DefineComponent, SlotsType } from 'vue'
type IslandComponent<T extends DefineComponent> = T & DefineComponent<{}, {refresh: () => Promise<void>}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, SlotsType<{ fallback: { error: unknown } }>>
interface _GlobalComponents {
      'EnumsCommonEnum': typeof import("../components/enums/common-enum")['default']
    'LayoutMainContent': typeof import("../components/layout/main-content.vue")['default']
    'LayoutMainContentWorkExperienceCardModal': typeof import("../components/layout/main-content/work-experience-card-modal.vue")['default']
    'LayoutMainFooter': typeof import("../components/layout/main-footer.vue")['default']
    'LayoutMainHeader': typeof import("../components/layout/main-header.vue")['default']
    'LayoutMenuDrawer': typeof import("../components/layout/menu-drawer.vue")['default']
    'LayoutMyComponentsAllComponents': typeof import("../components/layout/my-components/all-components.vue")['default']
    'LayoutMyComponentsButtonGroup': typeof import("../components/layout/my-components/button-group.vue")['default']
    'LayoutMyComponentsInputGroup': typeof import("../components/layout/my-components/input-group.vue")['default']
    'LayoutMyComponentsMyComponentScreen': typeof import("../components/layout/my-components/my-component-screen.vue")['default']
    'UiCustomCarrouselCard': typeof import("../components/ui/custom/carrousel/carrousel-card.vue")['default']
    'UiCustomCarrousel': typeof import("../components/ui/custom/carrousel/carrousel.vue")['default']
    'UiCustomColorThemeToggle': typeof import("../components/ui/custom/color-theme-toggle.vue")['default']
    'UiCustomCommonButton': typeof import("../components/ui/custom/common/button.vue")['default']
    'UiCustomCommonCard': typeof import("../components/ui/custom/common/card.vue")['default']
    'UiCustomCommonDropdown': typeof import("../components/ui/custom/common/dropdown.vue")['default']
    'UiCustomCommonInputCheckbox': typeof import("../components/ui/custom/common/input/checkbox.vue")['default']
    'UiCustomCommonInputDateInput': typeof import("../components/ui/custom/common/input/date-input.vue")['default']
    'UiCustomCommonInputTextInput': typeof import("../components/ui/custom/common/input/text-input.vue")['default']
    'UiCustomCommonLoader': typeof import("../components/ui/custom/common/loader.vue")['default']
    'UiCustomCommonModal': typeof import("../components/ui/custom/common/modal.vue")['default']
    'UiCustomCommonSlider': typeof import("../components/ui/custom/common/slider.vue")['default']
    'UiCustomCommonTable': typeof import("../components/ui/custom/common/table.vue")['default']
    'UiCustomCommonToggle': typeof import("../components/ui/custom/common/toggle.vue")['default']
    'NuxtWelcome': typeof import("../node_modules/nuxt/dist/app/components/welcome")['default']
    'NuxtLayout': typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
    'NuxtErrorBoundary': typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
    'ClientOnly': typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
    'DevOnly': typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
    'ServerPlaceholder': typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
    'NuxtLink': typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
    'NuxtLoadingIndicator': typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
    'NuxtRouteAnnouncer': typeof import("../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
    'NuxtImg': typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
    'NuxtPicture': typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
    'NuxtPage': typeof import("../node_modules/nuxt/dist/pages/runtime/page-placeholder")['default']
    'NoScript': typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
    'Link': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
    'Base': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
    'Title': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
    'Meta': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
    'Style': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
    'Head': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
    'Html': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
    'Body': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
    'NuxtIsland': typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
    'NuxtRouteAnnouncer': IslandComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']>
      'LazyEnumsCommonEnum': typeof import("../components/enums/common-enum")['default']
    'LazyLayoutMainContent': typeof import("../components/layout/main-content.vue")['default']
    'LazyLayoutMainContentWorkExperienceCardModal': typeof import("../components/layout/main-content/work-experience-card-modal.vue")['default']
    'LazyLayoutMainFooter': typeof import("../components/layout/main-footer.vue")['default']
    'LazyLayoutMainHeader': typeof import("../components/layout/main-header.vue")['default']
    'LazyLayoutMenuDrawer': typeof import("../components/layout/menu-drawer.vue")['default']
    'LazyLayoutMyComponentsAllComponents': typeof import("../components/layout/my-components/all-components.vue")['default']
    'LazyLayoutMyComponentsButtonGroup': typeof import("../components/layout/my-components/button-group.vue")['default']
    'LazyLayoutMyComponentsInputGroup': typeof import("../components/layout/my-components/input-group.vue")['default']
    'LazyLayoutMyComponentsMyComponentScreen': typeof import("../components/layout/my-components/my-component-screen.vue")['default']
    'LazyUiCustomCarrouselCard': typeof import("../components/ui/custom/carrousel/carrousel-card.vue")['default']
    'LazyUiCustomCarrousel': typeof import("../components/ui/custom/carrousel/carrousel.vue")['default']
    'LazyUiCustomColorThemeToggle': typeof import("../components/ui/custom/color-theme-toggle.vue")['default']
    'LazyUiCustomCommonButton': typeof import("../components/ui/custom/common/button.vue")['default']
    'LazyUiCustomCommonCard': typeof import("../components/ui/custom/common/card.vue")['default']
    'LazyUiCustomCommonDropdown': typeof import("../components/ui/custom/common/dropdown.vue")['default']
    'LazyUiCustomCommonInputCheckbox': typeof import("../components/ui/custom/common/input/checkbox.vue")['default']
    'LazyUiCustomCommonInputDateInput': typeof import("../components/ui/custom/common/input/date-input.vue")['default']
    'LazyUiCustomCommonInputTextInput': typeof import("../components/ui/custom/common/input/text-input.vue")['default']
    'LazyUiCustomCommonLoader': typeof import("../components/ui/custom/common/loader.vue")['default']
    'LazyUiCustomCommonModal': typeof import("../components/ui/custom/common/modal.vue")['default']
    'LazyUiCustomCommonSlider': typeof import("../components/ui/custom/common/slider.vue")['default']
    'LazyUiCustomCommonTable': typeof import("../components/ui/custom/common/table.vue")['default']
    'LazyUiCustomCommonToggle': typeof import("../components/ui/custom/common/toggle.vue")['default']
    'LazyNuxtWelcome': typeof import("../node_modules/nuxt/dist/app/components/welcome")['default']
    'LazyNuxtLayout': typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
    'LazyNuxtErrorBoundary': typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
    'LazyClientOnly': typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
    'LazyDevOnly': typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
    'LazyServerPlaceholder': typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
    'LazyNuxtLink': typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
    'LazyNuxtLoadingIndicator': typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
    'LazyNuxtRouteAnnouncer': typeof import("../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
    'LazyNuxtImg': typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
    'LazyNuxtPicture': typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
    'LazyNuxtPage': typeof import("../node_modules/nuxt/dist/pages/runtime/page-placeholder")['default']
    'LazyNoScript': typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
    'LazyLink': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
    'LazyBase': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
    'LazyTitle': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
    'LazyMeta': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
    'LazyStyle': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
    'LazyHead': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
    'LazyHtml': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
    'LazyBody': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
    'LazyNuxtIsland': typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
    'LazyNuxtRouteAnnouncer': IslandComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']>
}

declare module 'vue' {
  export interface GlobalComponents extends _GlobalComponents { }
}

export const EnumsCommonEnum: typeof import("../components/enums/common-enum")['default']
export const LayoutMainContent: typeof import("../components/layout/main-content.vue")['default']
export const LayoutMainContentWorkExperienceCardModal: typeof import("../components/layout/main-content/work-experience-card-modal.vue")['default']
export const LayoutMainFooter: typeof import("../components/layout/main-footer.vue")['default']
export const LayoutMainHeader: typeof import("../components/layout/main-header.vue")['default']
export const LayoutMenuDrawer: typeof import("../components/layout/menu-drawer.vue")['default']
export const LayoutMyComponentsAllComponents: typeof import("../components/layout/my-components/all-components.vue")['default']
export const LayoutMyComponentsButtonGroup: typeof import("../components/layout/my-components/button-group.vue")['default']
export const LayoutMyComponentsInputGroup: typeof import("../components/layout/my-components/input-group.vue")['default']
export const LayoutMyComponentsMyComponentScreen: typeof import("../components/layout/my-components/my-component-screen.vue")['default']
export const UiCustomCarrouselCard: typeof import("../components/ui/custom/carrousel/carrousel-card.vue")['default']
export const UiCustomCarrousel: typeof import("../components/ui/custom/carrousel/carrousel.vue")['default']
export const UiCustomColorThemeToggle: typeof import("../components/ui/custom/color-theme-toggle.vue")['default']
export const UiCustomCommonButton: typeof import("../components/ui/custom/common/button.vue")['default']
export const UiCustomCommonCard: typeof import("../components/ui/custom/common/card.vue")['default']
export const UiCustomCommonDropdown: typeof import("../components/ui/custom/common/dropdown.vue")['default']
export const UiCustomCommonInputCheckbox: typeof import("../components/ui/custom/common/input/checkbox.vue")['default']
export const UiCustomCommonInputDateInput: typeof import("../components/ui/custom/common/input/date-input.vue")['default']
export const UiCustomCommonInputTextInput: typeof import("../components/ui/custom/common/input/text-input.vue")['default']
export const UiCustomCommonLoader: typeof import("../components/ui/custom/common/loader.vue")['default']
export const UiCustomCommonModal: typeof import("../components/ui/custom/common/modal.vue")['default']
export const UiCustomCommonSlider: typeof import("../components/ui/custom/common/slider.vue")['default']
export const UiCustomCommonTable: typeof import("../components/ui/custom/common/table.vue")['default']
export const UiCustomCommonToggle: typeof import("../components/ui/custom/common/toggle.vue")['default']
export const NuxtWelcome: typeof import("../node_modules/nuxt/dist/app/components/welcome")['default']
export const NuxtLayout: typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
export const NuxtErrorBoundary: typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
export const ClientOnly: typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
export const DevOnly: typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
export const ServerPlaceholder: typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
export const NuxtLink: typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
export const NuxtLoadingIndicator: typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
export const NuxtRouteAnnouncer: typeof import("../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
export const NuxtImg: typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
export const NuxtPicture: typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
export const NuxtPage: typeof import("../node_modules/nuxt/dist/pages/runtime/page-placeholder")['default']
export const NoScript: typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
export const Link: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
export const Base: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
export const Title: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
export const Meta: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
export const Style: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
export const Head: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
export const Html: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
export const Body: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
export const NuxtIsland: typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
export const NuxtRouteAnnouncer: IslandComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']>
export const LazyEnumsCommonEnum: typeof import("../components/enums/common-enum")['default']
export const LazyLayoutMainContent: typeof import("../components/layout/main-content.vue")['default']
export const LazyLayoutMainContentWorkExperienceCardModal: typeof import("../components/layout/main-content/work-experience-card-modal.vue")['default']
export const LazyLayoutMainFooter: typeof import("../components/layout/main-footer.vue")['default']
export const LazyLayoutMainHeader: typeof import("../components/layout/main-header.vue")['default']
export const LazyLayoutMenuDrawer: typeof import("../components/layout/menu-drawer.vue")['default']
export const LazyLayoutMyComponentsAllComponents: typeof import("../components/layout/my-components/all-components.vue")['default']
export const LazyLayoutMyComponentsButtonGroup: typeof import("../components/layout/my-components/button-group.vue")['default']
export const LazyLayoutMyComponentsInputGroup: typeof import("../components/layout/my-components/input-group.vue")['default']
export const LazyLayoutMyComponentsMyComponentScreen: typeof import("../components/layout/my-components/my-component-screen.vue")['default']
export const LazyUiCustomCarrouselCard: typeof import("../components/ui/custom/carrousel/carrousel-card.vue")['default']
export const LazyUiCustomCarrousel: typeof import("../components/ui/custom/carrousel/carrousel.vue")['default']
export const LazyUiCustomColorThemeToggle: typeof import("../components/ui/custom/color-theme-toggle.vue")['default']
export const LazyUiCustomCommonButton: typeof import("../components/ui/custom/common/button.vue")['default']
export const LazyUiCustomCommonCard: typeof import("../components/ui/custom/common/card.vue")['default']
export const LazyUiCustomCommonDropdown: typeof import("../components/ui/custom/common/dropdown.vue")['default']
export const LazyUiCustomCommonInputCheckbox: typeof import("../components/ui/custom/common/input/checkbox.vue")['default']
export const LazyUiCustomCommonInputDateInput: typeof import("../components/ui/custom/common/input/date-input.vue")['default']
export const LazyUiCustomCommonInputTextInput: typeof import("../components/ui/custom/common/input/text-input.vue")['default']
export const LazyUiCustomCommonLoader: typeof import("../components/ui/custom/common/loader.vue")['default']
export const LazyUiCustomCommonModal: typeof import("../components/ui/custom/common/modal.vue")['default']
export const LazyUiCustomCommonSlider: typeof import("../components/ui/custom/common/slider.vue")['default']
export const LazyUiCustomCommonTable: typeof import("../components/ui/custom/common/table.vue")['default']
export const LazyUiCustomCommonToggle: typeof import("../components/ui/custom/common/toggle.vue")['default']
export const LazyNuxtWelcome: typeof import("../node_modules/nuxt/dist/app/components/welcome")['default']
export const LazyNuxtLayout: typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
export const LazyNuxtErrorBoundary: typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
export const LazyClientOnly: typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
export const LazyDevOnly: typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
export const LazyServerPlaceholder: typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
export const LazyNuxtLink: typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
export const LazyNuxtLoadingIndicator: typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
export const LazyNuxtRouteAnnouncer: typeof import("../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
export const LazyNuxtImg: typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
export const LazyNuxtPicture: typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
export const LazyNuxtPage: typeof import("../node_modules/nuxt/dist/pages/runtime/page-placeholder")['default']
export const LazyNoScript: typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
export const LazyLink: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
export const LazyBase: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
export const LazyTitle: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
export const LazyMeta: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
export const LazyStyle: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
export const LazyHead: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
export const LazyHtml: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
export const LazyBody: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
export const LazyNuxtIsland: typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
export const LazyNuxtRouteAnnouncer: IslandComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']>

export const componentNames: string[]
